# Default settings for can4rpc
# For details on Rocket configuration, see:
#  https://rocket.rs/v0.4/guide/configuration/#configuratio

[server]
address = "localhost"
port = 8000
keep_alive = 5
log = "normal"
# limits = { forms = 32768 }

# Settings for Git
[git]
webhook_secret = "secret"
username = "ci-user"
ssh_key = "/etc/ssh-keys/labhub-key.ecdsa"
api_token = "token"
hostname = "github.com"
