[package]
name = "toc-uv"
version = "0.1.0"
authors = ["Sascha Smolkov <sascha.smolkov@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# console

console = "0.7.5"
syntect = "*"
indicatif = "*"

[[lib]]
