language: rust
sudo: false
rust:
  - 1.26.0
  - stable
  - beta
  - nightly

os:
  - linux
  - osx

addons:
  apt:
    packages:
      - libcurl4-openssl-dev
      - libelf-dev
      - libdw-dev
      - binutils-dev

before_script:
  - pip2 install 'travis-cargo<0.2' --user

env:
  global:
    - TRAVIS_CARGO_NIGHTLY_FEATURE=""
    - PATH="$(python -m site --user-base)/bin:$PATH"
    - secure: "Ez5eIIgmsfNoV9NQ9H6KrAYX/Dxx6EUQEyyLMoSFvgJuMaPsyWlsDQDKbl9G+aNDNdSWYtYVFc4/fCW+H7a13HjVwB2CH2mChHSeguO8FSAkWns8tkZ+71SKL5/hg3Ig2m+kvfDjjV1O8seFEgTDP3enHFoRTmBSZHeNryo1ITM="

script:
  - |
    travis-cargo build -- --features=tokio &&
    travis-cargo test -- --features=tokio &&
    travis-cargo build -- --features=mio-evented &&
    travis-cargo test -- --features=mio-evented &&
    travis-cargo build -- &&
    travis-cargo test -- &&
    travis-cargo --only stable doc -- --features=tokio

after_success:
  - '[ $TRAVIS_OS_NAME == linux ] && travis-cargo coveralls --no-sudo --verify'
